import * as crypto from 'crypto';
import * as fs from 'fs';
import { SSL_FOLDER_PATH } from './ssl';
import { getLogger } from '../logger';
import * as jwt from 'jsonwebtoken';

const keypairRootPath = SSL_FOLDER_PATH;
const jwtPrivKey = keypairRootPath + "/jwt_priv.pem"
const jwtPublicKey = keypairRootPath + "/jwt_pub.pem"
const jwtKeypairLength = 4096;

const logger = getLogger("jwt-helper");

export type Keypair = {
    privKey: string,
    pubKey: string
}

const JWT_KEYPAIR: Keypair = {
    privKey: "<not set>",
    pubKey: "<not set>"
}

export function generateRsaKeyPair(bitsize: number): Keypair {
    const keypair = crypto.generateKeyPairSync('rsa', {
        modulusLength: bitsize,
        publicKeyEncoding: {
            type: 'spki',
            format: 'pem'
        },
        privateKeyEncoding: {
            type: 'pkcs1',
            format: 'pem'
            // cipher: 'aes-256-cbc'
            // passphrase: undefined
        }
    });

    return {
        privKey: keypair.privateKey,
        pubKey: keypair.publicKey,
    }
}

export function initJwtBackend() {
    logger.info("Initializing JWT backend...");
    if (!fs.existsSync(jwtPrivKey) || !fs.existsSync(jwtPublicKey)) {
        logger.info("We don't yet have a RSA keypair for generating/validating JWT tokens. Generating a new one...");
        // we need to generate a new keypair that is used to sign JWTs generated by our backend (f.e. for email unsubscription links).
        const keypair = generateRsaKeyPair(jwtKeypairLength);
        fs.writeFileSync(jwtPrivKey, keypair.privKey, {encoding: 'utf-8'});
        fs.writeFileSync(jwtPublicKey, keypair.pubKey, {encoding: 'utf-8'});
        // TODO: Check file permissions... somehow.
        JWT_KEYPAIR.privKey = keypair.privKey;
        JWT_KEYPAIR.pubKey = keypair.pubKey;
        logger.info("Generated a new JWT keypair!");
    } else {
        logger.info("JWT keypair already exists! Reading in keypair...");
        JWT_KEYPAIR.privKey = fs.readFileSync(jwtPrivKey, {encoding: 'utf-8'});
        JWT_KEYPAIR.pubKey = fs.readFileSync(jwtPublicKey, {encoding: 'utf-8'});
        logger.info("Successfully read JWT keypair!");
    }
}

export function generateJWTtoken(payload: object) {
    return jwt.sign(payload, JWT_KEYPAIR.privKey, {algorithm: 'RS256'});
}

export function validateJWTtokenExtractPayload(jwtToken: string): object {
    try {
        const payload = jwt.verify(jwtToken, JWT_KEYPAIR.pubKey, {algorithms: ['RS256']},);
        return payload as object;
    } catch(e) {
        logger.warn("Tried to validate invalid JWT token!", {token: jwtToken, error: new String(e)});
        return undefined;
    }
}